name: Build LaTeX CV

on: [push]

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4.5.0

      - name: Create the .tex file
        run: |
          python script/create_cv.py

      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@master
        with:
          root_file: cv.tex
          args: -pdf -file-line-error -interaction=nonstopmode

      - name: Commit the new PDF
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add cv.pdf
          git commit -m "New CV version"

      - name: Push the PDF
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
